// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqkxWD4iKwgNxqqe8x4bsGzr0QySRWH8g',
    appId: '1:809130551458:web:ce18ddce539d100cf80ffb',
    messagingSenderId: '809130551458',
    projectId: 'campuscompanion-8e232',
    authDomain: 'campuscompanion-8e232.firebaseapp.com',
    storageBucket: 'campuscompanion-8e232.firebasestorage.app',
    measurementId: 'G-RQ49G7BD90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmylaFriM_z8jGHqcH6nrQtmCnfVSpWxk',
    appId: '1:809130551458:android:a1852d3fef569ad9f80ffb',
    messagingSenderId: '809130551458',
    projectId: 'campuscompanion-8e232',
    storageBucket: 'campuscompanion-8e232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoQxJJzHG8Jmc4PTnOdjQHBj7IKROl8b4',
    appId: '1:809130551458:ios:459892fe5709d8d4f80ffb',
    messagingSenderId: '809130551458',
    projectId: 'campuscompanion-8e232',
    storageBucket: 'campuscompanion-8e232.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoQxJJzHG8Jmc4PTnOdjQHBj7IKROl8b4',
    appId: '1:809130551458:ios:459892fe5709d8d4f80ffb',
    messagingSenderId: '809130551458',
    projectId: 'campuscompanion-8e232',
    storageBucket: 'campuscompanion-8e232.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqkxWD4iKwgNxqqe8x4bsGzr0QySRWH8g',
    appId: '1:809130551458:web:4022d9393a011a2cf80ffb',
    messagingSenderId: '809130551458',
    projectId: 'campuscompanion-8e232',
    authDomain: 'campuscompanion-8e232.firebaseapp.com',
    storageBucket: 'campuscompanion-8e232.firebasestorage.app',
    measurementId: 'G-NCWXM3MTJ8',
  );
}
